spring:
  application:
    name: clinexa-ehr-inventory

  datasource:
    url: jdbc:${DB_TYPE:postgresql}://${DB_HOST:localhost}:${DB_PORT:5435}/${DB_NAME:clinexa-patients-db}
    username: ${DB_USER_NAME:clinexa-patients-admin}
    password: ${DB_USER_PASSWORD:clinexa2026$}
  jpa:
    hibernate:
      ddl-auto: update

  ai:
    openai:
      api-key: ${OPENAI_API_KEY:}
      chat:
        options:
          model: gpt-5.4-mini
          max-completion-tokens: 100
          temperature: 0.5
    chat:
      memory:
        repository:
          jdbc:
            initialize-schema: ALWAYS #By default, schema initialization runs only for embedded databases
server:
  port: 6020
